name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello, Thank you for opening your first issue in our repository. We're here to help you with any questions or concerns you may have."
        pr-message: "Welcome, Thank you for your first interaction with our repository. We appreciate your contribution!"
